language: C

install:
  - CHANNEL=http://eupsforge.net/conda/dev ./install.sh lsst-sims pandas nose
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - setup lsst_sims
cache:
  directories:
  - $HOME/miniconda.tarball

# A trivial example to show that this worked
script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source eups-setups.sh
  - setup lsst_sims
  - nosetests -v

